import Image from "next/image";
import Link from "next/link";
import { heroImage } from "@/lib/images";

export default function Home() {
  return (
    <main className="flex flex-col min-h-screen">
      {/* Hero */}
      <section className="relative h-screen flex items-end">
        <Image
          src={heroImage.url}
          alt={heroImage.alt}
          fill
          className="object-cover object-top"
          priority
          sizes="100vw"
        />
        <div className="absolute inset-0 bg-gradient-to-t from-[#0a0a0a] via-[#0a0a0a]/40 to-transparent" />
        <div className="relative z-10 w-full px-6 pb-16 md:px-12 md:pb-24 max-w-3xl">
          <h1 className="text-5xl md:text-7xl font-bold tracking-tight mb-4">
            Sasha <span className="text-accent">Noire</span>
          </h1>
          <p className="text-lg md:text-xl text-white/70 mb-8 max-w-md">
            Bold. Raw. Beautiful.
          </p>
          <div className="flex flex-wrap gap-4">
            <a
              href="https://instagram.com/sashanoire.official"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 bg-accent text-black font-semibold px-6 py-3 rounded-full hover:bg-accent-dark transition-colors"
            >
              <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
                <path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zM12 0C8.741 0 8.333.014 7.053.072 2.695.272.273 2.69.073 7.052.014 8.333 0 8.741 0 12c0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98C8.333 23.986 8.741 24 12 24c3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98C15.668.014 15.259 0 12 0zm0 5.838a6.162 6.162 0 100 12.324 6.162 6.162 0 000-12.324zM12 16a4 4 0 110-8 4 4 0 010 8zm6.406-11.845a1.44 1.44 0 100 2.881 1.44 1.44 0 000-2.881z" />
              </svg>
              Follow on Instagram
            </a>
            <Link
              href="/gallery"
              className="inline-flex items-center gap-2 border border-white/20 text-white font-semibold px-6 py-3 rounded-full hover:border-accent/50 hover:text-accent transition-colors"
            >
              View Gallery
            </Link>
          </div>
        </div>
      </section>

      {/* About teaser */}
      <section className="px-6 py-20 md:px-12 md:py-32 max-w-4xl mx-auto text-center">
        <p className="text-2xl md:text-3xl font-light leading-relaxed text-white/80">
          <span className="text-accent font-medium">Generated by AI.</span>{" "}
          Curated daily. The work doesn&apos;t fit anywhere else.
        </p>
      </section>

      {/* Quick links */}
      <section className="px-6 py-16 md:px-12 border-t border-white/10">
        <div className="max-w-2xl mx-auto grid grid-cols-1 sm:grid-cols-3 gap-4">
          <Link
            href="/gallery"
            className="group flex flex-col items-center gap-2 p-6 rounded-2xl border border-white/10 hover:border-accent/30 transition-colors"
          >
            <span className="text-2xl">&#128248;</span>
            <span className="font-medium group-hover:text-accent transition-colors">Gallery</span>
          </Link>
          <Link
            href="/links"
            className="group flex flex-col items-center gap-2 p-6 rounded-2xl border border-white/10 hover:border-accent/30 transition-colors"
          >
            <span className="text-2xl">&#128279;</span>
            <span className="font-medium group-hover:text-accent transition-colors">Links</span>
          </Link>
          <a
            href="https://www.fanvue.com/sashanoire.official"
            target="_blank"
            rel="noopener noreferrer"
            className="group flex flex-col items-center gap-2 p-6 rounded-2xl border border-white/10 hover:border-accent/30 transition-colors"
          >
            <span className="text-2xl">&#11088;</span>
            <span className="font-medium group-hover:text-accent transition-colors">Subscribe</span>
          </a>
        </div>
      </section>

      {/* Footer */}
      <footer className="mt-auto px-6 py-8 border-t border-white/10 text-center text-sm text-white/40">
        <p>&copy; {new Date().getFullYear()} Sasha Noire. All rights reserved.</p>
      </footer>
    </main>
  );
}
